require("luozx")
require("luozx.plugins-setup")
require("luozx.set")
require("luozx.keymap")
require("luozx.plugins.comment")
require("luozx.plugins.lualine")
require("luozx.plugins.telescope")
require("luozx.plugins.nvim-cmp")
require("luozx.plugins.lsp.mason")
require("luozx.plugins.lsp.lspsaga")
require("luozx.plugins.lsp.lspconfig")
require("luozx.plugins.lsp.null-ls")
require("luozx.plugins.autopairs")
require("luozx.plugins.treesitter")
-- require("luozx.plugins.vimslime")
--require("luozx.plugins.swenv")
